#!/usr/bin/env python3
"""fyx_sort — self-contained correctness + stress + benchmark runner.

The C++ sources live inside this file, so the script is the whole deliverable:
drop it next to a copy of fyx_sort.hpp (or point it at one) and run it.

    python3 fyx_test.py                  # find the header, build, run everything
    python3 fyx_test.py --header ../fyx_sort.hpp
    python3 fyx_test.py --compiler clang++ --std c++20
    python3 fyx_test.py --bench           # add the throughput matrix
    python3 fyx_test.py --rlimit-mb 512   # re-run under a hard memory cap
    python3 fyx_test.py --keep            # keep the generated sources

Exit status is 0 when every check passes.
"""

import argparse
import os
import shutil
import subprocess
import sys
import tempfile

CPP = r"""// ---------------------------------------------------------------------------
// fyx_sort embedded suite: correctness, comparators, containers, stress.
// Generated by fyx_test.py -- edit the .py, not this file.
// ---------------------------------------------------------------------------
#include "fyx_sort.hpp"

#include <algorithm>
#include <atomic>
#include <cmath>
#include <cstdint>
#include <cstdio>
#include <cstring>
#include <deque>
#include <functional>
#include <limits>
#include <list>
#include <memory>
#include <random>
#include <stdexcept>
#include <string>
#include <thread>
#include <vector>

static int g_checks = 0;
static int g_fails  = 0;
static const char* g_section = "";
#define CHECK(cond, msg)                                                      \
    do {                                                                      \
        ++g_checks;                                                           \
        if (!(cond)) { std::printf("  FAIL [%s] %s\n", g_section, msg); ++g_fails; } \
    } while (0)

static std::mt19937_64 rng(0xF00DBAAD1234567ULL);

// ---------------------------------------------------------------------------
// shapes, all built on a sorted base so the disorder is controlled
// ---------------------------------------------------------------------------
// The base is a sorted run of values, so the disorder each shape adds is the
// only thing under test.  Strings get the same shapes through fixed-width
// keys, which makes the string order the numeric order of the underlying value.
template <class T>
static T make_value(std::size_t i) { return static_cast<T>(i % 1000003); }
template <>
std::string make_value<std::string>(std::size_t i) {
    char buf[32];
    std::snprintf(buf, sizeof buf, "key_%020zu", i % 1000003);
    return buf;
}

template <class T>
static std::vector<T> make_shape(const char* s, std::size_t n) {
    std::vector<T> v(n);
    for (std::size_t i = 0; i < n; ++i) v[i] = make_value<T>(i);
    std::sort(v.begin(), v.end());
    const std::string name(s);
    if (name == "sorted")      return v;
    if (name == "reversed")    { std::reverse(v.begin(), v.end()); return v; }
    if (name == "allequal")    { for (auto& x : v) x = make_value<T>(7); return v; }
    if (name == "twovalues")   { for (auto& x : v) x = make_value<T>((std::size_t)(&x - v.data()) % 2); return v; }
    if (name == "rotate")      { std::rotate(v.begin(), v.begin() + n / 3, v.end()); return v; }
    if (name == "organ")       { std::reverse(v.begin(), v.begin() + n / 2); return v; }
    if (name == "three_runs")  { std::reverse(v.begin() + n / 3, v.begin() + 2 * n / 3); return v; }
    if (name == "sawtooth")    { for (std::size_t i = 0; i + 4 <= n; i += 4) std::swap(v[i + 1], v[i + 2]); return v; }
    if (name == "local_swap")  { for (std::size_t k = 0; k + 1 < n / 500; ++k) { std::size_t i = rng() % (n - 66); std::swap(v[i], v[i + 1 + rng() % 64]); } return v; }
    if (name == "far_swap")    { for (std::size_t k = 0; k + 1 < n / 500; ++k) std::swap(v[rng() % n], v[rng() % n]); return v; }
    if (name == "block_move")  { const std::size_t bs = 128, nb = n / bs;
                                 for (int k = 0; k < 16 && nb > 4; ++k) { std::size_t i = rng() % (nb - 1); std::size_t j = std::min(nb - 1, i + 1 + rng() % 4);
                                   for (std::size_t t = 0; t < bs; ++t) std::swap(v[i * bs + t], v[j * bs + t]); } return v; }
    if (name == "splice")      { std::rotate(v.begin(), v.begin() + n / 7, v.begin() + n / 7 + n / 9); return v; }
    if (name == "affix")       { if (n > 20) std::shuffle(v.begin() + n / 2 - n / 10, v.begin() + n / 2 + n / 10, rng); return v; }
    if (name == "interleave")  { std::vector<T> a(v.begin(), v.begin() + n / 2), b(v.begin() + n / 2, v.end());
                                 for (std::size_t i = 0; i < n / 2; ++i) { v[2 * i] = a[i]; v[2 * i + 1] = b[i]; } return v; }
    if (name == "dup16")       { for (auto& x : v) x = make_value<T>(rng() % 16); return v; }
    if (name == "dup256")      { for (auto& x : v) x = make_value<T>(rng() % 256); return v; }
    if (name == "random")      { std::shuffle(v.begin(), v.end(), rng); return v; }
    std::printf("  (unknown shape %s)\n", s);
    return v;
}

template <class T>
static bool same_multiset(std::vector<T> a, std::vector<T> b) {
    if (a.size() != b.size()) return false;
    std::sort(a.begin(), a.end());
    std::sort(b.begin(), b.end());
    return a == b;
}

// Floating point is compared through the radix key: std::sort cannot express
// the total order fyx documents for -0 / +0 and NaN.
static bool double_ok(const std::vector<double>& got, const std::vector<double>& src) {
    using RT = fyx::detail::RadixTraits<double>;
    std::vector<std::uint64_t> a(got.size()), b(src.size());
    for (std::size_t i = 0; i < got.size(); ++i) a[i] = RT::encode(got[i]);
    for (std::size_t i = 0; i < src.size(); ++i) b[i] = RT::encode(src[i]);
    std::sort(b.begin(), b.end());
    return a == b;
}

// ---------------------------------------------------------------------------
// 1. every shape, every type, serial and parallel
// ---------------------------------------------------------------------------
template <class T>
static void sweep(const char* tname, std::size_t n) {
    const char* shapes[] = {"sorted", "reversed", "allequal", "twovalues", "rotate", "organ",
                            "three_runs", "sawtooth", "local_swap", "far_swap", "block_move",
                            "splice", "affix", "interleave", "dup16", "dup256", "random"};
    for (const char* s : shapes) {
        rng.seed(0xF00DBAAD1234567ULL);
        const std::vector<T> base = make_shape<T>(s, n);
        for (int mode = 0; mode < 2; ++mode) {
            std::vector<T> v = base;
            fyx::Options o;
            o.parallel = mode ? fyx::Tri::On : fyx::Tri::Off;
            fyx::sort(v, o);
            const bool ordered = std::is_sorted(v.begin(), v.end());
            CHECK(ordered, (std::string(tname) + " " + s + (mode ? " (par) order" : " (ser) order")).c_str());
            CHECK(same_multiset(v, base), (std::string(tname) + " " + s + (mode ? " (par) multiset" : " (ser) multiset")).c_str());
        }
    }
}

static void sweep_double(std::size_t n) {
    const char* shapes[] = {"sorted", "reversed", "allequal", "rotate", "organ", "local_swap",
                            "far_swap", "block_move", "affix", "dup16", "random"};
    for (const char* s : shapes) {
        rng.seed(0xF00DBAAD1234567ULL);
        const std::vector<double> base = make_shape<double>(s, n);
        for (int mode = 0; mode < 2; ++mode) {
            std::vector<double> v = base;
            fyx::Options o;
            o.parallel = mode ? fyx::Tri::On : fyx::Tri::Off;
            fyx::sort(v, o);
            CHECK(double_ok(v, base), (std::string("double ") + s + (mode ? " (par)" : " (ser)")).c_str());
        }
    }
}

// ---------------------------------------------------------------------------
// 2. sizes: the small end, and either side of every dispatch threshold
// ---------------------------------------------------------------------------
static void check_sizes() {
    std::vector<std::size_t> sizes;
    for (std::size_t n = 0; n <= 64; ++n) sizes.push_back(n);
    for (std::size_t b : {size_t(128), size_t(256), size_t(512), size_t(1024), size_t(2048),
                          size_t(4096), size_t(8192), size_t(16384), size_t(65536),
                          size_t(262144), size_t(1u << 19), size_t(1u << 21)}) {
        sizes.push_back(b - 1); sizes.push_back(b); sizes.push_back(b + 1);
    }
    for (std::size_t n : sizes) {
        rng.seed(0x1234ULL + n);
        std::vector<std::int32_t> v = make_shape<std::int32_t>(n % 3 == 0 ? "random" : (n % 3 == 1 ? "sorted" : "local_swap"), n);
        const std::vector<std::int32_t> base = v;
        fyx::sort(v);
        CHECK(std::is_sorted(v.begin(), v.end()), "size sweep order");
        CHECK(same_multiset(v, base), "size sweep multiset");
    }
    // odd sizes on a type the vectoriser would like to see aligned
    struct Odd {
        std::uint8_t b[13];
        bool operator<(const Odd& o) const { return std::memcmp(b, o.b, 13) < 0; }
        bool operator==(const Odd& o) const { return std::memcmp(b, o.b, 13) == 0; }
    };
    for (std::size_t n : {size_t(0), size_t(1), size_t(17), size_t(1000), size_t(4097)}) {
        std::vector<Odd> v(n);
        for (std::size_t i = 0; i < n; ++i) v[i].b[0] = static_cast<std::uint8_t>((i * 7919u) & 0xFFu);
        const std::vector<Odd> base = v;
        fyx::sort(v);
        CHECK(std::is_sorted(v.begin(), v.end()), "odd-size payload order");
        CHECK(same_multiset(v, base), "odd-size payload multiset");
    }
}

// ---------------------------------------------------------------------------
// 3. comparators: descending, custom, NaN / -0 / +0, move-only payloads
// ---------------------------------------------------------------------------
struct Key {
    int k;
    int payload;
    bool operator<(const Key& o) const { return k < o.k; }
    bool operator==(const Key& o) const { return k == o.k && payload == o.payload; }
};
static void check_comparators() {
    const std::size_t n = 200000;
    {   std::vector<int> v = make_shape<int>("random", n);
        const std::vector<int> base = v;
        fyx::sort(v, std::greater<int>());
        CHECK(std::is_sorted(v.begin(), v.end(), std::greater<int>()), "descending comparator order");
        CHECK(same_multiset(v, base), "descending comparator multiset");
    }
    {   std::vector<Key> v(n);
        for (std::size_t i = 0; i < n; ++i) { v[i].k = static_cast<int>(rng() % 1000); v[i].payload = static_cast<int>(i); }
        const std::vector<Key> base = v;
        fyx::sort(v, [](const Key& a, const Key& b) { return a.k < b.k; });
        bool ok = std::is_sorted(v.begin(), v.end(), [](const Key& a, const Key& b) { return a.k < b.k; });
        CHECK(ok, "custom comparator on a struct");
        // Only the key is ordered, so only the key can be compared: the sort
        // is unstable and the payload order is therefore unspecified.
        std::vector<int> ka, kb;
        for (auto& x : v) ka.push_back(x.k);
        for (auto& x : base) kb.push_back(x.k);
        CHECK(same_multiset(ka, kb), "custom comparator keeps the elements");
    }
    {   std::vector<double> v;
        const double nan = std::numeric_limits<double>::quiet_NaN();
        for (int i = 0; i < 4000; ++i) v.push_back(static_cast<double>(i % 50) - 25.0);
        for (int i = 0; i < 40; ++i) { v.push_back(nan); v.push_back(-0.0); v.push_back(0.0); }
        v.push_back(std::numeric_limits<double>::infinity());
        v.push_back(-std::numeric_limits<double>::infinity());
        std::shuffle(v.begin(), v.end(), rng);
        const std::vector<double> base = v;
        fyx::sort(v);
        CHECK(double_ok(v, base), "NaN / -0 / +0 / inf keep the documented total order");
    }
    {   // move-only payloads: the weapons must not need a copy anywhere
        std::vector<std::unique_ptr<int>> v;
        for (int i = 0; i < 50000; ++i) v.push_back(std::unique_ptr<int>(new int(static_cast<int>(rng() % 100000))));
        std::vector<int> expect;
        for (auto& p : v) expect.push_back(*p);
        std::sort(expect.begin(), expect.end());
        fyx::sort(v, [](const std::unique_ptr<int>& a, const std::unique_ptr<int>& b) { return *a < *b; });
        std::vector<int> got;
        for (auto& p : v) got.push_back(*p);
        CHECK(got == expect, "move-only payloads sort");
    }
}

// ---------------------------------------------------------------------------
// 4. containers, including the ones whose storage is not one block
// ---------------------------------------------------------------------------
static void check_containers() {
    const std::size_t n = 100000;
    {   std::vector<int> v = make_shape<int>("random", n);
        const std::vector<int> base = v;
        fyx::sort(v);
        CHECK(std::is_sorted(v.begin(), v.end()) && same_multiset(v, base), "std::vector");
    }
    {   std::vector<int> v = make_shape<int>("random", n);
        const std::vector<int> base = v;
        fyx::sort(v.begin(), v.end());
        CHECK(std::is_sorted(v.begin(), v.end()) && same_multiset(v, base), "vector iterators");
    }
    {   std::array<int, 100000> a{};
        for (std::size_t i = 0; i < a.size(); ++i) a[i] = static_cast<int>((rng() % 100000));
        const std::vector<int> base(a.begin(), a.end());
        fyx::sort(a);
        CHECK(std::is_sorted(a.begin(), a.end()) && same_multiset(std::vector<int>(a.begin(), a.end()), base), "std::array");
    }
    {   std::string s;
        for (std::size_t i = 0; i < n; ++i) s.push_back(static_cast<char>('a' + rng() % 26));
        std::string base = s;
        fyx::sort(s);
        std::sort(base.begin(), base.end());
        CHECK(s == base, "std::string");
    }
    {   std::deque<int> d;
        for (std::size_t i = 0; i < n; ++i) d.push_back(static_cast<int>(rng() % 100000));
        const std::vector<int> base(d.begin(), d.end());
        fyx::sort(d);
        CHECK(std::is_sorted(d.begin(), d.end()) && same_multiset(std::vector<int>(d.begin(), d.end()), base),
              "std::deque (segmented storage)");
    }
    {   std::deque<int> d;
        for (std::size_t i = 0; i < n; ++i) d.push_back(static_cast<int>(rng() % 100000));
        const std::vector<int> base(d.begin(), d.end());
        fyx::sort(d.begin(), d.end());
        CHECK(std::is_sorted(d.begin(), d.end()) && same_multiset(std::vector<int>(d.begin(), d.end()), base),
              "std::deque iterators");
    }
    {   std::list<int> l;
        for (std::size_t i = 0; i < 20000; ++i) l.push_back(static_cast<int>(rng() % 100000));
        const std::vector<int> base(l.begin(), l.end());
        fyx::sort(l);
        CHECK(std::is_sorted(l.begin(), l.end()) && same_multiset(std::vector<int>(l.begin(), l.end()), base),
              "std::list");
    }
    {   int raw[50000];
        for (int& x : raw) x = static_cast<int>(rng() % 100000);
        std::vector<int> base(raw, raw + 50000);
        fyx::sort(raw, raw + 50000);
        CHECK(std::is_sorted(raw, raw + 50000) && same_multiset(std::vector<int>(raw, raw + 50000), base),
              "raw array, pointer + length");
    }
}

// ---------------------------------------------------------------------------
// 5. stress: the environments where a sorter usually breaks
// ---------------------------------------------------------------------------

/// (a) A comparator that lies.  It must not hang, not crash and not lose or
///     duplicate an element -- it may produce any order it likes, because no
///     order satisfies an inconsistent comparator.
static void stress_inconsistent_comparator() {
    const std::size_t n = 100000;
    std::vector<int> v(n);
    for (auto& x : v) x = static_cast<int>(rng() % 1000);
    const std::vector<int> base = v;
    // Every key compares equal, and equal keys also compare less: a strict
    // weak ordering violation that a partitioning loop can spin on.
    fyx::sort(v, [](const int&, const int&) { return true; });
    CHECK(same_multiset(v, base), "inconsistent comparator keeps every element");
    std::vector<int> w = base;
    fyx::sort(w, [](const int& a, const int& b) { return (a & 1) < (b & 1); });   // not transitive
    CHECK(same_multiset(w, base), "non-transitive comparator keeps every element");
}

/// (b) Exceptions.  A throwing comparator or a throwing move must propagate out
///     of fyx::sort, and the range must still hold every element exactly once:
///     no leaks, no duplicates, no destroyed-and-reused slots.
struct Counted {
    static std::atomic<long> live;
    static std::atomic<long> moves;
    int v;
    explicit Counted(int x) : v(x) { ++live; }
    Counted(const Counted& o) : v(o.v) { ++live; }
    Counted(Counted&& o) noexcept(false) : v(o.v) {
        ++moves;
        // A constructor that throws leaves no object behind -- so the live
        // count must only go up once the throw point is behind us.
        if (throw_after.fetch_sub(1) == 1) throw std::runtime_error("move");
        ++live;
    }
    Counted& operator=(Counted&& o) noexcept(false) {
        ++moves;
        if (throw_after.fetch_sub(1) == 1) throw std::runtime_error("move assign");
        v = o.v;
        return *this;
    }
    Counted& operator=(const Counted& o) { v = o.v; return *this; }
    ~Counted() { --live; }
    static std::atomic<long> throw_after;
    Counted() : v(0) { ++live; }
    bool operator<(const Counted& o) const { return v < o.v; }
    bool operator==(const Counted& o) const { return v == o.v; }
};
std::atomic<long> Counted::live{0};
std::atomic<long> Counted::moves{0};
std::atomic<long> Counted::throw_after{0};

static void stress_exceptions() {
    const std::size_t n = 20000;
    for (long trip = 1; trip <= 40; ++trip) {
        std::vector<Counted> v;
        v.reserve(n + 16);
        for (std::size_t i = 0; i < n; ++i) v.emplace_back(static_cast<int>(rng() % 10000));
        Counted::throw_after.store(trip * 7);
        const long live_before = Counted::live.load();
        bool threw = false;
        try {
            fyx::sort(v.begin(), v.end());
        } catch (const std::runtime_error&) {
            threw = true;
        }
        Counted::throw_after.store(0);
        // The vector still owns n live objects: whatever the sort did, it did
        // not leave holes behind or duplicate an element.
        CHECK(static_cast<std::size_t>(v.size()) == n, "throwing move leaves the size alone");
        CHECK(Counted::live.load() == live_before, "throwing move leaks no element");
        (void)threw;
        // Re-sorting the (possibly disturbed) range must still work.
        try {
            fyx::sort(v.begin(), v.end());
            CHECK(std::is_sorted(v.begin(), v.end()), "range sorts after an exception");
        } catch (const std::runtime_error&) {
            // thrown again from a later trip point: still fine
        }
    }
    {   // a comparator that throws
        std::vector<int> v(n);
        for (auto& x : v) x = static_cast<int>(rng() % 10000);
        std::vector<int> base = v;
        std::atomic<long> budget{500};
        bool threw = false;
        try {
            fyx::sort(v, [&](int a, int b) {
                if (budget.fetch_sub(1) == 1) throw std::runtime_error("cmp");
                return a < b;
            });
        } catch (const std::runtime_error&) {
            threw = true;
        }
        CHECK(same_multiset(v, base), "throwing comparator keeps every element");
    }
}

/// (c) Reentrancy: sorting from inside a comparator.  The scratch arena is
///     thread-local and leased, so a nested sort must fall back cleanly.
static void stress_reentrant() {
    const std::size_t n = 50000;
    std::vector<int> v(n);
    for (auto& x : v) x = static_cast<int>(rng() % 1000);
    const std::vector<int> base = v;
    int depth = 0;
    fyx::sort(v, [&](int a, int b) {
        if (depth < 2) {
            ++depth;
            std::vector<int> inner(2048);
            for (auto& x : inner) x = static_cast<int>(rng() % 1000);
            fyx::sort(inner);
            if (!std::is_sorted(inner.begin(), inner.end())) ++g_fails;
            --depth;
        }
        return a < b;
    });
    CHECK(std::is_sorted(v.begin(), v.end()), "reentrant sort: outer range");
    CHECK(same_multiset(v, base), "reentrant sort: outer multiset");
}

/// (d) Many threads sorting at once: the pool and the arena are shared.
static void stress_threads() {
    const int threads = 8;
    const std::size_t n = 120000;
    std::atomic<int> bad{0};
    std::vector<std::thread> ts;
    try {
    for (int t = 0; t < threads; ++t) {
        ts.emplace_back([&, t] {
            std::mt19937_64 g(0xABCULL + t);
            for (int rep = 0; rep < 6; ++rep) {
                std::vector<std::int64_t> v(n);
                for (auto& x : v) x = static_cast<std::int64_t>(g() % 1000000);
                std::vector<std::int64_t> base = v;
                fyx::Options o;
                o.parallel = (rep % 2) ? fyx::Tri::On : fyx::Tri::Off;
                fyx::sort(v, o);
                if (!std::is_sorted(v.begin(), v.end())) ++bad;
                if (!same_multiset(v, base)) ++bad;
            }
        });
    }
    for (auto& t : ts) t.join();
    CHECK(bad.load() == 0, "eight threads sorting at once");
    } catch (const std::system_error&) {
        // Under a hard address-space cap (--rlimit-mb) even a thread stack
        // cannot be reserved.  That is the environment failing, not the sort,
        // so the check is skipped rather than reported as a failure.
        for (auto& t : ts) if (t.joinable()) t.join();
        std::printf("  (thread stress skipped: no room for %d stacks)\n", threads);
    }
}

/// (e) The same input sorted repeatedly must give the same answer: catches
///     uninitialised scratch and reading past an array end.
static void stress_determinism() {
    const std::size_t n = 150000;
    std::vector<std::int32_t> first;
    for (int rep = 0; rep < 25; ++rep) {
        rng.seed(0xDEADBEEFULL);
        std::vector<std::int32_t> v = make_shape<std::int32_t>("block_move", n);
        fyx::sort(v);
        if (rep == 0) first = v;
        else if (v != first) { CHECK(false, "repeated sorts of the same input agree"); return; }
        CHECK(std::is_sorted(v.begin(), v.end()), "repeated sorts stay sorted");
    }
}

/// (f) Pathological value distributions.
static void stress_values() {
    const std::size_t n = 200000;
    {   std::vector<std::int64_t> v(n, std::numeric_limits<std::int64_t>::min());
        for (std::size_t i = 0; i < n; i += 2) v[i] = std::numeric_limits<std::int64_t>::max();
        fyx::sort(v);
        CHECK(std::is_sorted(v.begin(), v.end()), "extreme integer values");
    }
    {   std::vector<double> v;
        for (std::size_t i = 0; i < n; ++i) v.push_back(std::numeric_limits<double>::denorm_min() * static_cast<double>(1 + i % 7));
        fyx::sort(v);
        CHECK(double_ok(v, v), "denormals sort");
    }
    {   std::vector<std::string> v;
        for (std::size_t i = 0; i < 40000; ++i) v.push_back(std::string(1, static_cast<char>('a' + rng() % 4))); // 4 distinct
        std::vector<std::string> base = v;
        fyx::sort(v);
        CHECK(std::is_sorted(v.begin(), v.end()) && same_multiset(v, base), "very low cardinality strings");
    }
    {   std::vector<std::string> v;   // long shared prefixes: comparison is expensive
        for (std::size_t i = 0; i < 20000; ++i) v.push_back(std::string(200, 'x') + std::to_string(rng() % 100000));
        std::vector<std::string> base = v;
        fyx::sort(v);
        CHECK(std::is_sorted(v.begin(), v.end()) && same_multiset(v, base), "long shared-prefix strings");
    }
}

// ---------------------------------------------------------------------------
// 6. throughput matrix (--bench)
// ---------------------------------------------------------------------------
static void bench() {
    const std::size_t n = 1000000;
    std::mt19937_64 g(7);
    auto timed = [](auto fn) {
        double best = 1e9;
        for (int r = 0; r < 3; ++r) {
            auto t0 = std::chrono::steady_clock::now();
            (void)fn();
            auto t1 = std::chrono::steady_clock::now();
            best = std::min(best, std::chrono::duration<double>(t1 - t0).count());
        }
        return best;
    };
    const char* shapes[] = {"random", "sorted", "reversed", "allequal", "local_swap", "far_swap",
                            "block_move", "affix", "rotate", "organ", "dup16", "sawtooth"};
    std::printf("\n%-13s %-9s %-9s %-9s %-9s\n", "shape", "fyx ser", "fyx par", "std", "gain");
    for (const char* s : shapes) {
        rng.seed(0xF00DULL);
        const std::vector<std::int32_t> base = make_shape<std::int32_t>(s, n);
        double fs = timed([&] { auto v = base; fyx::Options o; o.parallel = fyx::Tri::Off; fyx::sort(v, o); return std::is_sorted(v.begin(), v.end()); });
        double fp = timed([&] { auto v = base; fyx::Options o; o.parallel = fyx::Tri::On;  fyx::sort(v, o); return std::is_sorted(v.begin(), v.end()); });
        double st = timed([&] { auto v = base; std::sort(v.begin(), v.end()); return true; });
        std::printf("%-13s %-9.5f %-9.5f %-9.5f %-9.2fx\n", s, fs, fp, st, st / fp);
    }
}

/// (g) Sorting with no memory headroom.  Everything is allocated before the
///     cap is applied by the wrapper, so the only thing under test is whether
///     fyx::sort degrades instead of dying when it cannot get scratch, buffers
///     or worker threads.
static int mem_only() {
    const std::size_t n = 2000000;
    static std::vector<std::int32_t> pool(n);
    static std::vector<std::int32_t> src(n);
    for (auto& x : src) x = static_cast<std::int32_t>(rng() & 0x7FFFFFFF);
    {
        std::copy(src.begin(), src.end(), pool.begin());
        fyx::sort(pool);
        CHECK(std::is_sorted(pool.begin(), pool.end()), "serial sort with no memory headroom");
    }
    {
        std::copy(src.begin(), src.end(), pool.begin());
        fyx::Options o;
        o.parallel = fyx::Tri::On;
        fyx::sort(pool, o);
        CHECK(std::is_sorted(pool.begin(), pool.end()), "parallel sort with no memory headroom");
    }
    std::printf("checks=%d failures=%d\n", g_checks, g_fails);
    if (g_fails == 0) { std::printf("MEM OK\n"); return 0; }
    return 1;
}

int main(int argc, char** argv) {
    if (argc > 1 && std::string(argv[1]) == "--mem") return mem_only();
    const bool do_bench = argc > 1 && std::string(argv[1]) == "--bench";
    const std::size_t n = 200000;

    g_section = "shapes";
    sweep<std::int32_t>("int32", n);
    sweep<std::int64_t>("int64", n);
    sweep<std::uint64_t>("uint64", n);
    sweep<double>("double", n);
    sweep<std::string>("string", n / 2);
    sweep_double(n);
    std::printf("  shapes: %d checks\n", g_checks);

    g_section = "sizes";   check_sizes();
    g_section = "cmp";     check_comparators();
    g_section = "cont";    check_containers();

    g_section = "stress";
    stress_inconsistent_comparator();
    stress_exceptions();
    stress_reentrant();
    stress_threads();
    stress_determinism();
    stress_values();

    if (do_bench) bench();

    std::printf("\nchecks=%d failures=%d\n", g_checks, g_fails);
    if (g_fails == 0) { std::printf("ALL FYX TESTS PASS\n"); return 0; }
    std::printf("FYX TEST FAILURES=%d\n", g_fails);
    return 1;
}
"""


def find_header(explicit=None):
    if explicit:
        p = os.path.abspath(explicit)
        if not os.path.isfile(p):
            sys.exit("fyx_test.py: header not found: %s" % p)
        return p
    here = os.path.dirname(os.path.abspath(__file__))
    for cand in (os.path.join(here, "fyx_sort.hpp"),
                 os.path.join(here, os.pardir, "fyx_sort.hpp"),
                 os.path.join(os.getcwd(), "fyx_sort.hpp"),
                 os.path.join(here, os.pardir, os.pardir, "fyx_sort.hpp")):
        if os.path.isfile(cand):
            return os.path.abspath(cand)
    sys.exit("fyx_test.py: could not find fyx_sort.hpp -- pass --header PATH")


def pick_compiler(want=None):
    cands = [want] if want else []
    cands += [os.environ.get("CXX"), "g++", "clang++", "c++"]
    for c in cands:
        if c and shutil.which(c):
            return c
    sys.exit("fyx_test.py: no C++ compiler found (tried %s)" % ", ".join(x for x in cands if x))


def compiler_supports(cc, flag, std):
    try:
        r = subprocess.run([cc, "-std=" + std, "-x", "c++", flag, "-fsyntax-only", "-"],
                           input="int main(){}\n", text=True,
                           stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        return r.returncode == 0
    except Exception:
        return False


def build(cc, std, header, src, exe, extra):
    cmd = [cc, "-std=" + std, "-O2", "-pthread", "-I" + os.path.dirname(header), src, "-o", exe] + extra
    print("  compile: " + " ".join(cmd))
    r = subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)
    if r.returncode != 0:
        print(r.stdout)
        sys.exit("fyx_test.py: compilation failed")
    return True


def run(exe, args, rlimit_mb=None):
    cmd = [exe] + args
    if rlimit_mb:
        # ulimit -v caps the address space: every scratch allocation path in
        # the library has to fall back instead of aborting.
        cmd = ["bash", "-c", "ulimit -v %d; exec %s" % (rlimit_mb * 1024, " ".join(cmd))]
    print("  run:     " + " ".join(cmd))
    r = subprocess.run(cmd)
    return r.returncode


def main():
    ap = argparse.ArgumentParser(description="fyx_sort self-contained test runner")
    ap.add_argument("--header", help="path to fyx_sort.hpp")
    ap.add_argument("--compiler", help="C++ compiler")
    ap.add_argument("--std", default="c++17")
    ap.add_argument("--bench", action="store_true", help="also run the throughput matrix")
    ap.add_argument("--rlimit-mb", type=int, help="re-run the suite under this address-space cap")
    ap.add_argument("--keep", action="store_true", help="keep the generated sources")
    ap.add_argument("--outdir")
    a = ap.parse_args()

    header = find_header(a.header)
    cc = pick_compiler(a.compiler)
    print("fyx_test.py")
    print("  header:  %s" % header)
    print("  compiler:%s  (-std=%s)" % (cc, a.std))

    extra = []
    for flag in ("-march=native",):
        if compiler_supports(cc, flag, a.std):
            extra.append(flag)
    if compiler_supports(cc, "-fsanitize=address,undefined", a.std) and os.environ.get("FYX_ASAN"):
        extra.append("-fsanitize=address,undefined")

    work = a.outdir or tempfile.mkdtemp(prefix="fyx_test_")
    os.makedirs(work, exist_ok=True)
    src = os.path.join(work, "fyx_embedded_test.cpp")
    with open(src, "w") as f:
        f.write(CPP)
    exe = os.path.join(work, "fyx_embedded_test")
    if os.path.exists(exe):
        os.remove(exe)

    build(cc, a.std, header, src, exe, extra)

    args = ["--bench"] if a.bench else []
    rc = run(exe, args)
    if rc != 0 and not a.bench:
        print("fyx_test.py: suite FAILED (exit %d)" % rc)

    if a.rlimit_mb:
        print("\nfyx_test.py: memory-cap probe under a %d MB address space" % a.rlimit_mb)
        rc2 = run(exe, ["--mem"], rlimit_mb=a.rlimit_mb)
        if rc2 != 0:
            print("fyx_test.py: the suite did not survive the memory cap (exit %d)" % rc2)
        rc = rc or rc2

    if a.keep:
        print("\nfyx_test.py: sources kept in %s" % work)
    elif not a.outdir:
        shutil.rmtree(work, ignore_errors=True)
    sys.exit(rc)


if __name__ == "__main__":
    main()
